title: Redacted
email: example@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A website for Redacted
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: none
github_username:  juilie
marquee_text: "REDACTED"

plugins:
  - jekyll-feed

plugins_dir:
  - _plugins

collections:
  works:
    output: true
  performances:
    output: true
  press:
    output: true

include:
  - static